# Generated by Django 5.2.2 on 2025-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(help_text="Evento:", max_length=100)),
                ("codigo", models.IntegerField(help_text="Código do ingresso:")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço:", max_digits=8
                    ),
                ),
            ],
        ),
    ]
