# Generated by Django 5.2.3 on 2025-06-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Evento:", max_length=100)),
                ("codigo", models.IntegerField(help_text="Código do ingresso:")),
                (
                    "dtEvento",
                    models.DateField(help_text="Data do evento no formato DD/MM/AAAA:"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço:", max_digits=8
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
