# Generated by Django 5.2.3 on 2025-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingressos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Evento:", max_length=100)),
                ("codigo", models.IntegerField(help_text="Código do ingresso:")),
                (
                    "dtEvento",
                    models.DateField(help_text="Data do evento no formato DD/MM/AAAA:"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, help_text="Preço:", max_digits=8
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Ingresso",
        ),
    ]
